[package]
name = "omsi-net"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
ureq = { version = "2", default-features = false, features = ["tls"] }
flate2 = "1"
sha2 = "0.10"
ring = "0.17"
tungstenite = { version = "0.26", default-features = false, features = ["handshake", "rustls-tls-webpki-roots"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
